config/routes.rb
Rails.application.routes.draw do
  resources :shops
  resources :cars
  
  resource :user, only: [] do 
    get "sign_up"
    post "register"

    get "sign_in"
    post "login"

    delete "logout"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "landing#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  validates :make, :model, :year, :price, :odometer, presence: true
  validates :year, numericality: { less_than_or_equal_to: Time.now.year }
  validates :odometer, numericality: {greater_than: 0 }
  belongs_to :shop
  belongs_to :user 

  after_create do 
    shop.cars_count += 1
    shop.save 
  end

  after_destroy do 
    shop.cars_count -= 1
    shop.save
  end
 
end

app/models/shop.rb
class Shop < ApplicationRecord
   has_many :cars
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cars

  PASSWORD_FORMAT = /\A
  (?=.{8,}) 
  (?=.*\d)
  (?=.*[a-z])
  (?=.*[A-Z])
  (?=.*[:])
/x

  validates :first_name, :last_name, :email, :password_digest, presence: true
  validates :email, format: {with: /@/, message: "hasn't @"}, uniqueness: true
  validates :password_digest, format: {with: PASSWORD_FORMAT}
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    @current_user ||= User.find_by(id: session[:current_user_id])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @shops = Shop.all.map { |shop| [shop.name, shop.id] }
    @car = Car.new
    @user = session[:current_user_id]
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)
    @car.user_id = session[:current_user_id]

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        @shops = Shop.all.map { |shop| [shop.name, shop.id] }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    if @car.user_id == session[:current_user_id] || @user.admin == true 
      respond_to do |format|
        if @car.update(car_params)
          format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
          format.json { render :show, status: :ok, location: @car }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      end
    else

    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    if @car.user_id == session[:current_user_id] || @user.admin == true 
      @car.destroy

      respond_to do |format|
        format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to cars_url, notice: "This car can only be removed by the creator." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:make, :model, :year, :price, :odometer, :shop_id, :user_id)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]

  # GET /shops or /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1 or /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:address, :name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_up
    @user = User.new   
  end

  def sign_in 
    
  end

  def register 
    @user = User.new(user_params)
    
    if @user.save 
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      render "sign_up"
    end
  end
  
  def login 
    @user = User.find_by(email: params[:email], password_digest: params[:password_digest])

    if @user 
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      @error = true
      render "sign_in"
    end
  end

  def logout 
    session[:current_user_id] = nil
    redirect_to root_path
  end

  private 

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Make:</strong>
    <%= car.make %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= car.model %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= car.year %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= car.price %>
  </p>

  <p>
    <strong>Odometer:</strong>
    <%= car.odometer %>
  </p>

  <p>
    <strong>Shop:</strong>
    <%= car.shop.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= car.user_id %>
  </p>

</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :make, style: "display: block" %>
    <%= form.text_field :make %>
  </div>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :odometer, style: "display: block" %>
    <%= form.number_field :odometer %>
  </div>

  <div>
    <%= form.label :shop, style: "display: block"%>
    <%= form.select :shop_id, @shops %>
  </div> 

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>
      <%= button_to "logout", logout_user_path, method: :delete%>
      <%= link_to "shops", shops_path%>
<h1>Cars</h1>

<div id="cars">
  <% @cars.each do |car| %>
    <%= render car %>
    <p>
      <%= link_to "Show this car", car %>
    </p>
  <% end %>
</div>

<%= link_to "New car", new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div>
  <%= link_to "Edit this car", edit_car_path(@car) %> |
  <%= link_to "Back to cars", cars_path %>

  <%= button_to "Destroy this car", @car, method: :delete %>
</div>

app/views/landing/index.html.erb
<div class="authorization">
  <% if @current_user %>
      welcom,  <%= @current_user.first_name %>
      <%= button_to "logout", logout_user_path, method: :delete%>
      <%= link_to "cars", cars_path%>
      <%= link_to "shops", shops_path%>
    <% else %>
      <p><%= link_to "sign up", sign_up_user_path%></p>
      <p><%= link_to "sign in", sign_in_user_path%></p>
  <%end%> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/shops/_form.html.erb
<%= form_with(model: shop) do |form| %>
  <% if shop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<div id="<%= dom_id shop %>">
  <p>
    <strong>Address:</strong>
    <%= shop.address %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= shop.name %>
  </p>
  
  <p>
    <strong>Cars count:</strong>
    <%= shop.cars_count %>
  </p>

  <p>
    <strong>Country:</strong>
    <% country = shop.name %>
     <%= country.split()[-1] %>
  </p>

  <p>
    <strong>Cars:</strong>
    <% shop.cars.each do |car| %>
    <p><%= car.make %> <%= car.model%> <%= car.year %></p>
    <%end%>
  </p>

</div>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Show this shop", @shop %> |
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/index.html.erb
<p style="color: green"><%= notice %></p>
  <%= button_to "logout", logout_user_path, method: :delete%>
  <%= link_to "cars", cars_path%>
<h1>Shops</h1>

<div id="shops">
  <% @shops.each do |shop| %>
    <%= render shop %>
    <p>
      <%= link_to "Show this shop", shop %>
    </p>
  <% end %>
</div>

<%= link_to "New shop", new_shop_path %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shop %>

<div>
  <%= link_to "Edit this shop", edit_shop_path(@shop) %> |
  <%= link_to "Back to shops", shops_path %>

  <%= button_to "Destroy this shop", @shop, method: :delete %>
</div>

app/views/users/sign_in.html.erb
<%= form_with(url: login_user_path) do |form|%>
  <% if @error %>
    <div style = "color: red">
      <h2>no user with such email/password</h2>
    </div>
  <%end%>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.password_field :password_digest %>
  </div>

  <%= form.submit %>
<%end%>

app/views/users/sign_up.html.erb
<%= form_with(model: @user, url: register_user_path) do |form|%>
<% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.password_field :password_digest %>
  </div>

  <div>
    <%= form.submit %>
  </div>

  <%end%>